# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('client_type', models.CharField(choices=[('driver', 'Driver'), ('passenger', 'Passenger'), ('slipflall', 'Slipfall')], help_text='Enter the type of client', max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=14, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(help_text='Enter the type of incident', max_length=50)),
                ('summary', models.TextField(help_text='Enter a short description of the incident', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='incident',
            field=models.OneToOneField(help_text='Select a type of incident for the client', on_delete=django.db.models.deletion.CASCADE, to='autoaccident.Incident'),
        ),
    ]
