# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoaccident', '0005_auto_20170302_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaddress',
            name='client',
            field=models.OneToOneField(help_text='select client', null=True, on_delete=django.db.models.deletion.CASCADE, to='autoaccident.Client'),
        ),
    ]
