# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoaccident', '0006_auto_20170302_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_make', models.CharField(max_length=50, null=True)),
                ('vehicle_model', models.CharField(max_length=50, null=True)),
                ('vehicle_registration', models.CharField(max_length=7, null=True)),
                ('vehicle_color', models.CharField(max_length=50, null=True)),
                ('damage_location', models.TextField(help_text='Enter where the damage is on the vehicle', max_length=100, null=True)),
                ('damage_description', models.TextField(help_text='Enter a description of the damage', max_length=400, null=True)),
                ('client', models.OneToOneField(help_text='select client', null=True, on_delete=django.db.models.deletion.CASCADE, to='autoaccident.Client')),
            ],
        ),
    ]
