# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoaccident', '0007_clientvehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientvehicle',
            name='vehicle_year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
