# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('autoaccident', '0008_clientvehicle_vehicle_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular client across whole site', primary_key=True, serialize=False)),
                ('Statute_of_limitation', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('signin pending', 'Signin Pending'), ('property damage', 'Property Damage'), ('demand', 'Demand'), ('reject-1', 'Reject-1'), ('reject-2', 'Reject-2'), ('reject-3', 'Reject-3'), ('filed-in-court', 'filed-in-court'), ('other', 'Other')], default='pending', help_text='Case Status', max_length=50)),
            ],
            options={
                'ordering': ['Statute_of_limitation'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='date_of_accident',
            field=models.DateField(null=True, verbose_name='Date of Accident'),
        ),
        migrations.AddField(
            model_name='clientinstance',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='autoaccident.Client'),
        ),
    ]
