# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('autoaccident', '0010_auto_20170308_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_accident', models.DateField(null=True, verbose_name='Date of Accident')),
                ('time_of_accident', models.TimeField(null=True, verbose_name='Time of Accident')),
                ('city_of_accident', models.CharField(blank=True, default='Fullerton', max_length=64, null=True, verbose_name='city')),
                ('intersection_of_accident', models.CharField(blank=True, help_text='Provide the name of the street where the incident took place', max_length=150, null=True)),
                ('police_report', models.BooleanField(default=False, help_text='Did the police make a incident report?')),
                ('police_report_number', models.CharField(blank=True, max_length=15, null=True)),
                ('accident_description', models.TextField(help_text='Please enter a brief description of how the accident happened', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherPartyInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(blank=True, max_length=100, null=True)),
                ('passenger_phonenumber', models.CharField(max_length=14, null=True)),
                ('passenger_date_of_birth', models.DateField(null=True, verbose_name='Date of Birth')),
                ('passenger_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50, null=True)),
                ('passenger_driver_license', models.CharField(max_length=14, null=True)),
                ('passenger_address_1', models.CharField(blank=True, max_length=128, verbose_name='address')),
                ('passenger_address_2', models.CharField(blank=True, max_length=128, verbose_name="address cont'd")),
                ('passenger_city', models.CharField(default='Fullerton', max_length=64, null=True, verbose_name='city')),
                ('passenger_state', localflavor.us.models.USStateField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AS', 'American Samoa'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('AA', 'Armed Forces Americas'), ('AE', 'Armed Forces Europe'), ('AP', 'Armed Forces Pacific'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('MP', 'Northern Mariana Islands'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VI', 'Virgin Islands'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='CA', max_length=2)),
                ('passenger_zip_code', models.CharField(blank=True, max_length=5, verbose_name='zip code')),
                ('passenger_vehicle_year', models.CharField(max_length=4, null=True)),
                ('passenger_vehicle_make', models.CharField(max_length=50, null=True)),
                ('passenger_vehicle_model', models.CharField(max_length=50, null=True)),
                ('passenger_vehicle_registration', models.CharField(max_length=7, null=True)),
                ('passenger_vehicle_color', models.CharField(max_length=50, null=True)),
                ('passenger_Carseat', models.BooleanField(default=True, help_text='Did you have a child carseat in the car?')),
                ('passenger_damage_location', models.TextField(help_text='Enter where the damage is on the vehicle', max_length=100, null=True)),
                ('passenger_damage_description', models.TextField(help_text='Enter a description of the damage', max_length=400, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='driver_license',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='number_of_passengers',
            field=models.IntegerField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='passengers',
            field=models.BooleanField(default=False, help_text='Any passengers in the car?'),
        ),
        migrations.AddField(
            model_name='clientvehicle',
            name='Carseat',
            field=models.BooleanField(default=True, help_text='Did you have a child carseat in the car?'),
        ),
        migrations.AddField(
            model_name='otherpartyinformation',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='autoaccident.Client'),
        ),
        migrations.AddField(
            model_name='accidentdetails',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='autoaccident.Client'),
        ),
    ]
