# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoaccident', '0011_auto_20170313_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otherpartyinformation',
            old_name='passenger_Carseat',
            new_name='otherparty_Carseat',
        ),
        migrations.RenameField(
            model_name='otherpartyinformation',
            old_name='passenger_address_1',
            new_name='otherparty_address_1',
        ),
        migrations.RenameField(
            model_name='otherpartyinformation',
            old_name='passenger_address_2',
            new_name='otherparty_address_2',
        ),
        migrations.RenameField(
            model_name='otherpartyinformation',
            old_name='passenger_city',
            new_name='otherparty_city',
        ),
        migrations.RenameField(
            model_name='otherpartyinformation',
            old_name='passenger_damage_description',
            new_name='otherparty_damage_description',
        ),
        migrations.RenameField(
            model_name='otherpartyinformation',
            old_name='passenger_damage_location',
            new_name='otherparty_damage_location',
        ),
        migrations.RenameField(
            model_name='otherpartyinformation',
            old_name='passenger_date_of_birth',
            new_name='otherparty_date_of_birth',
        ),
        migrations.RenameField(
            model_name='otherpartyinformation',
            old_name='passenger_driver_license',
            new_name='otherparty_driver_license',
        ),
        migrations.RenameField(
            model_name='otherpartyinformation',
            old_name='passenger_name',
            new_name='otherparty_driver_name',
        ),
        migrations.RenameField(
            model_name='otherpartyinformation',
            old_name='passenger_gender',
            new_name='otherparty_gender',
        ),
        migrations.RenameField(
            model_name='otherpartyinformation',
            old_name='passenger_phonenumber',
            new_name='otherparty_phonenumber',
        ),
        migrations.RenameField(
            model_name='otherpartyinformation',
            old_name='passenger_state',
            new_name='otherparty_state',
        ),
        migrations.RenameField(
            model_name='otherpartyinformation',
            old_name='passenger_vehicle_color',
            new_name='otherparty_vehicle_color',
        ),
        migrations.RenameField(
            model_name='otherpartyinformation',
            old_name='passenger_vehicle_make',
            new_name='otherparty_vehicle_make',
        ),
        migrations.RenameField(
            model_name='otherpartyinformation',
            old_name='passenger_vehicle_model',
            new_name='otherparty_vehicle_model',
        ),
        migrations.RenameField(
            model_name='otherpartyinformation',
            old_name='passenger_vehicle_registration',
            new_name='otherparty_vehicle_registration',
        ),
        migrations.RenameField(
            model_name='otherpartyinformation',
            old_name='passenger_vehicle_year',
            new_name='otherparty_vehicle_year',
        ),
        migrations.RenameField(
            model_name='otherpartyinformation',
            old_name='passenger_zip_code',
            new_name='otherparty_zip_code',
        ),
        migrations.AddField(
            model_name='otherpartyinformation',
            name='otherparty_number_of_passengers',
            field=models.IntegerField(blank=True, max_length=8, null=True),
        ),
    ]
