# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoaccident', '0012_auto_20170315_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurnace_company', models.CharField(max_length=20, null=True)),
                ('Policy_holder_name', models.CharField(max_length=30, null=True)),
                ('policy_number', models.CharField(max_length=15, null=True)),
                ('type_of_coverage', models.CharField(choices=[('Liability only', 'liability only'), ('Comprehensive Coverage', 'comprehensive coverage'), ('Collision Coverage', 'collision coverage'), ('Uninsured/Underinsured Motorist', 'uninsured/underinsured motorist'), ('Medical Payments', 'medical payments'), ('Personal Injury Protection', 'personal injury protection')], max_length=20, null=True)),
                ('coverage_limit_pd', models.CharField(help_text='Enter the policy limit for property damage in dollars', max_length=8, null=True)),
                ('coverage_limit_medical', models.CharField(help_text='Enter the policy limit for medical in dollars', max_length=8, null=True)),
                ('other_insurnace_company', models.CharField(max_length=20, null=True)),
                ('other_Policy_holder_name', models.CharField(max_length=30, null=True)),
                ('other_policy_number', models.CharField(max_length=15, null=True)),
                ('other_type_of_coverage', models.CharField(choices=[('Liability only', 'liability only'), ('Comprehensive Coverage', 'comprehensive coverage'), ('Collision Coverage', 'collision coverage'), ('Uninsured/Underinsured Motorist', 'uninsured/underinsured motorist'), ('Medical Payments', 'medical payments'), ('Personal Injury Protection', 'personal injury protection')], max_length=20, null=True)),
                ('other_policy_limit_pd', models.CharField(help_text='Enter the policy limit for property damage in dollars', max_length=8, null=True)),
                ('other_policy_limit', models.CharField(help_text='Enter the policy limit per incident in dollars', max_length=8, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='accidentdetails',
            name='weather_condition',
            field=models.CharField(choices=[('sunny', 'Sunny'), ('cloudy', 'Cloudy'), ('rainy', 'Rainy')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='number_of_passengers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otherpartyinformation',
            name='otherparty_number_of_passengers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insuranceinformation',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='autoaccident.Client'),
        ),
    ]
