# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 01:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoaccident', '0013_auto_20170316_2309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientinstance',
            options={},
        ),
        migrations.RemoveField(
            model_name='clientinstance',
            name='Statute_of_limitation',
        ),
    ]
