# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoaccident', '0014_auto_20170321_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientvehicle',
            name='Carseat',
        ),
        migrations.AddField(
            model_name='clientvehicle',
            name='carseat',
            field=models.NullBooleanField(),
        ),
    ]
