# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoaccident', '0015_auto_20170328_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientvehicle',
            name='carseat',
        ),
    ]
