# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('autoaccident', '0018_remove_otherpartyinformation_otherparty_carseat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_appointment', models.CharField(choices=[('new_case', 'New Case'), ('existing_case', 'Existing Case'), ('property_damage_discussion', 'Property Damage Discussion'), ('medical_report', 'Medical Report'), ('signing_docs', 'Documents Signing'), ('docs_submit', 'Documents Subminssion'), ('settlement_discussion', 'Discussing the Settlement Offer'), ('sign_final_docs', 'To sign the settlement Documents'), ('check_collection', 'Check Collection'), ('status_inquiry', 'For Case Status'), ('other', 'Other')], max_length=100, null=True)),
                ('further_appointment_notes', models.TextField(max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=10, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('appointment_date', models.DateTimeField(blank=True, null=True)),
                ('appointment_time', models.TimeField(blank=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='autoaccident.Client')),
            ],
        ),
    ]
