# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 04:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoaccident', '0021_auto_20170402_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='client',
        ),
    ]
