# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoaccident', '0022_remove_appointment_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_name', models.CharField(max_length=100, null=True)),
                ('caller_number', models.CharField(max_length=10, null=True)),
                ('call_date', models.DateTimeField(blank=True, null=True)),
                ('call_notes', models.TextField(max_length=100, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='autoaccident.Client')),
            ],
        ),
    ]
