# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoaccident', '0023_calllog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=20, null=True)),
                ('hospital_number', models.CharField(max_length=10, null=True)),
                ('lien', models.BooleanField(default=False, help_text='lien signed?')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='injuries',
            field=models.TextField(help_text='list the injuries,eg. neck, back etc.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='autoaccident.Client'),
        ),
    ]
