# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoaccident', '0024_auto_20170405_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentdetails',
            name='date_of_accident',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentdetails',
            name='time_of_accident',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
