# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoaccident', '0025_auto_20170405_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insuranceinformation',
            old_name='Policy_holder_name',
            new_name='policy_holder_name',
        ),
        migrations.RemoveField(
            model_name='otherpartyinformation',
            name='otherparty_damage_description',
        ),
        migrations.RemoveField(
            model_name='otherpartyinformation',
            name='otherparty_damage_location',
        ),
        migrations.RemoveField(
            model_name='otherpartyinformation',
            name='otherparty_number_of_passengers',
        ),
        migrations.AddField(
            model_name='accidentdetails',
            name='emergency_treatment',
            field=models.BooleanField(default=False, help_text='Were you transported to ER?'),
        ),
        migrations.AddField(
            model_name='accidentdetails',
            name='er_facility_name',
            field=models.CharField(blank=True, help_text='Name of the ER hospital', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='accidentdetails',
            name='incident_photos',
            field=models.BooleanField(default=False, help_text='Pictures of the incident and/or vehicle?'),
        ),
        migrations.AddField(
            model_name='accidentdetails',
            name='paramedics',
            field=models.BooleanField(default=False, help_text='Paramedics come to the scene of accident?'),
        ),
        migrations.AddField(
            model_name='accidentdetails',
            name='urgentcare_facility_name',
            field=models.CharField(blank=True, help_text='Name of the urgentcare hospital', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='accidentdetails',
            name='urgentcare_treatment',
            field=models.BooleanField(default=False, help_text='Did the clientgo to any urgent care?'),
        ),
        migrations.AddField(
            model_name='accidentdetails',
            name='witness',
            field=models.BooleanField(default=False, help_text='Are there any witnesses of the incident?'),
        ),
        migrations.AddField(
            model_name='client',
            name='medicaid_coverage',
            field=models.BooleanField(default=False, help_text='Are you covered by Medicaid?'),
        ),
        migrations.AddField(
            model_name='client',
            name='medicare_coverage',
            field=models.BooleanField(default=False, help_text='Are you covered by Medicare?'),
        ),
        migrations.AddField(
            model_name='client',
            name='ssnumber',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='insuranceinformation',
            name='deductible',
            field=models.CharField(blank=True, help_text='collision coverage deductible in dollars', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='insuranceinformation',
            name='perday_rental',
            field=models.CharField(blank=True, help_text='Rental coverage per day in dollars', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='insuranceinformation',
            name='rental_coverage',
            field=models.BooleanField(default=False, help_text='Does clients insurance cover rental vehicle?'),
        ),
        migrations.AlterField(
            model_name='clientinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('signinpending', 'Signin Pending'), ('propertydamage', 'Property Damage'), ('pendingmedicalreport', 'Pending Medical Report'), ('demand', 'Demand'), ('reject-1', 'Reject-1'), ('reject-2', 'Reject-2'), ('reject-3', 'Reject-3'), ('pendingfiling', 'Pending Filing in Court'), ('filed-in-court', 'Filed in Court'), ('closed', 'Closed'), ('other', 'Other')], default='pending', help_text='Case Status', max_length=50),
        ),
    ]
