# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoaccident', '0028_calllog_date_of_accident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentdetails',
            name='er_facility_name',
            field=models.CharField(blank=True, default='N/A', help_text='Name of the ER hospital', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accidentdetails',
            name='urgentcare_facility_name',
            field=models.CharField(blank=True, default='N/A', help_text='Name of the urgentcare hospital', max_length=20, null=True),
        ),
    ]
