# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoaccident', '0029_auto_20170415_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insuranceinformation',
            old_name='insurnace_company',
            new_name='insurance_company',
        ),
        migrations.AlterField(
            model_name='accidentdetails',
            name='urgentcare_facility_name',
            field=models.CharField(blank=True, default='N', help_text='Name of the urgentcare hospital', max_length=20, null=True),
        ),
    ]
