# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoaccident', '0030_auto_20170418_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentdetails',
            name='weather_condition',
            field=models.CharField(choices=[('normal', 'Normal'), ('cloudy', 'Cloudy'), ('rainy', 'Rainy'), ('foggy', 'Foggy'), ('windy', 'Windy')], max_length=20, null=True),
        ),
    ]
