# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoaccident', '0032_auto_20170421_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceinformation',
            name='type_of_coverage',
            field=models.CharField(choices=[('Liability only', 'liability only'), ('Comprehensive Coverage', 'comprehensive coverage'), ('Collision Coverage', 'collision coverage'), ('Uninsured/Underinsured Motorist', 'uninsured/underinsured motorist'), ('Medical Payments', 'medical payments'), ('Personal Injury Protection', 'personal injury protection')], max_length=50, null=True),
        ),
    ]
