# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoaccident', '0033_auto_20170421_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='hospital_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceinformation',
            name='insurance_company',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
