# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoaccident', '0034_auto_20170422_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=20, null=True)),
                ('trial_Date', models.DateTimeField(blank=True, null=True)),
                ('osc_date', models.DateTimeField(blank=True, null=True)),
                ('cmc_date', models.DateTimeField(blank=True, null=True)),
                ('depo_date', models.DateTimeField(blank=True, null=True)),
                ('mediation_date', models.DateTimeField(blank=True, null=True)),
                ('arbitration_date', models.DateTimeField(blank=True, null=True)),
                ('final_status_conference', models.DateTimeField(blank=True, null=True)),
                ('trial_setting_conf_date', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='autoaccident.Client')),
            ],
        ),
    ]
