# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoaccident', '0035_courtcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='type_of_appointment',
            field=models.CharField(choices=[('New Case', 'New Case'), ('existing_case', 'Existing Case'), ('property_damage_discussion', 'Property Damage Discussion'), ('medical_report', 'Medical Report'), ('signing_docs', 'Documents Signing'), ('docs_submit', 'Documents Subminssion'), ('settlement_discussion', 'Discussing the Settlement Offer'), ('sign_final_docs', 'To sign the settlement Documents'), ('check_collection', 'Check Collection'), ('status_inquiry', 'For Case Status'), ('other', 'Other')], max_length=100, null=True),
        ),
    ]
