# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoaccident', '0036_auto_20170426_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='type_of_appointment',
            field=models.CharField(choices=[('New Case', 'New Case'), ('Existing Case', 'Existing Case'), ('Property Damage Discussion', 'Property Damage Discussion'), ('Medical Report', 'Medical Report'), ('Documents Signing', 'Documents Signing'), ('Documents Subminssion', 'Documents Subminssion'), ('Discussing the Settlement Offer', 'Discussing the Settlement Offer'), ('To sign the settlement Documents', 'To sign the settlement Documents'), ('Check Collection', 'Check Collection'), ('For Case Status', 'For Case Status'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
