# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoaccident', '0037_auto_20170426_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='otherpartyinformation',
            name='otherparty_phonenumber',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
