# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoaccident', '0039_auto_20170427_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='further_appointment_notes',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
