# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 19:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoaccident', '0040_auto_20170427_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='call_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
